### ISSUE TITLE
BCs aus REX5.13: Hook im Medienpool

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/focuspoint#108]
In REDAXO 5.13 gibt es Änderungen, die Focuspoint teilweise lahmlegen.

In der Detailseite des Medienpools wird das Vorschaubild in der Seitenleiste durch den Code für ein Bild mit interaktiver Auswahl der Fokuspunkte ersetzt. Da sich in R5.13 das HTML der Seite geändert hat, wird der Code nicht mehr gefunden und die Auswahl auch nicht aktiviert. 

In `focuspoint::show_sidebar` wird nach `rex_mediapool_maximized` gesucht; der neue Name ist `rex_media_large`. 

Wer eine schnelle Lösung sucht: in Zeile 79 den Code anpassen. 
https://github.com/FriendsOfREDAXO/focuspoint/blob/d4f7ad803220d9233971140dbbafecfa8c9c83a8/lib/focuspoint.php#L79

**Comment by olien** [comment]
Hm. Hat sich wieder etwas geändert?
Mit 5.13.0-beta2 geht es leider nicht...

**Comment by christophboecker** [comment]
Bin eben auf dasselbe Problem gelaufen. Die aktuelle Version läuft erst am 5.13.0, also auch nicht 5.13.beta x. Weil, wenn ich das nun richtig verstehe, 5.13.0-beta kleiner ist als 5.13.0? Daher geht die Abfrage auf '^5.13.0' wohl auch nicht richtig. Muss man statt dessen auf `>5.12.99' abfragen? @gharlan

**Comment by christophboecker** [comment]
Ich hab mal pragmatisch in der package.yml dies eingetragen:
```yml
requires:
    packages:
        media_manager: '>2.11.99'
        mediapool: '>2.10.99'
    redaxo: '>5.12.99'
    php:
        version: '>=7.3'
```
